### ISSUE TITLE
Unhandled Thrown Error!     Cannot read properties of undefined (reading 'categories')

### ISSUE THREAD

**Issue by MohitBansal321** [MohitBansal321/expense-tracker#1]
**When logged In  gets an error after refresh error has gone**
```
Unhandled Thrown Error!
Cannot read properties of undefined (reading 'categories')
TypeError: Cannot read properties of undefined (reading 'categories')
    at aP (https://statuesque-malasada-3def89.netlify.app/static/js/main.3f9f405d.js:2:735484)
    at Ci (https://statuesque-malasada-3def89.netlify.app/static/js/main.3f9f405d.js:2:143160)
    at Su (https://statuesque-malasada-3def89.netlify.app/static/js/main.3f9f405d.js:2:200400)
    at bs (https://statuesque-malasada-3def89.netlify.app/static/js/main.3f9f405d.js:2:189336)
    at gs (https://statuesque-malasada-3def89.netlify.app/static/js/main.3f9f405d.js:2:189264)
    at vs (https://statuesque-malasada-3def89.netlify.app/static/js/main.3f9f405d.js:2:189127)
    at as (https://statuesque-malasada-3def89.netlify.app/static/js/main.3f9f405d.js:2:185907)
    at us (https://statuesque-malasada-3def89.netlify.app/static/js/main.3f9f405d.js:2:186298)
    at Vo (https://statuesque-malasada-3def89.netlify.app/static/js/main.3f9f405d.js:2:126881)
    at https://statuesque-malasada-3def89.netlify.app/static/js/main.3f9f405d.js:2:183840
```    
Error getting from these lines
https://github.com/MohitBansal321/expense-tracker/blob/main/client/src/components/TransactionForm.js#L23
https://github.com/MohitBansal321/expense-tracker/blob/main/client/src/components/TransactionsList.js#L17

Steps to reproduce
Go to the site
Login 
See the error
reload error gone

**Comment by Nababratadeb-NITA** [comment]
it seems you did not defined the property name

**Comment by MohitBansal321** [comment]
can you fix this bug

**Comment by Nababratadeb-NITA** [comment]
Bro without knowing that where did you wrote the category function I can't help you

**Comment by MohitBansal321** [comment]
\controller\TransactionController.js   {backend}
or 
client\src\components\TransactionsList.js  {client}

**Comment by MohitBansal321** [comment]
t

> it seems you did not defined the property name

property name is defined but it didn't find on redux store

**Comment by MohitBansal321** [comment]
> Bro without knowing that where did you wrote the category function I can't help you

https://github.com/MohitBansal321/expense-tracker/blob/main/client/src/components/TransactionForm.js#L80-L83

**Comment by ChinmayMhatre** [comment]
I would suggest writing pure functions in the sense, pass all the required data as arguments. 

```js
function getCategoryNameById(categories,id) {
    return categories.find((category) => category._id === id) ?? null;
  }
```
Something like this

**Comment by MohitBansal321** [comment]
This category's data comes from the backend when the user login 
When I login on the browser it shows undefined but after refresh it was working fine   @ChinmayMhatre 
And I check the redux store the payload.user is undefined first time from which i am taking value of categories
after refresh payload.user is updated
